# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: cristiano100.roforge
PackageVersion: "0.1"
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -quiet -nolaunch
  SilentWithProgress: -quiet -nolaunch
  Upgrade: -upgrade
UpgradeBehavior: install
Protocols:
- roblox
- roblox-player
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/cristiano100/roforge/releases/latest/download/Roforge.exe
  InstallerSha256: 032E3293563EDCBA08BF52B887B2E34F2E9DF00FF310FA8046AE44BBE6A1B014
ManifestType: installer
ManifestVersion: 1.5.0
